// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmgjufiqvercuqfapegj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtZ2p1ZmlxdmVyY3VxZmFwZWdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MTY4MjIsImV4cCI6MjA2NTA5MjgyMn0.YhUV7KOg8sBSsaqxpCPMdHHcxn2jgoOUAdoiTHnrG-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});